### ISSUE TITLE
feat(dart_package): enable collecting functions and branch coverage

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_workflows#103]
## Function and branch coverage

To gather function level coverage information, pass `--function-coverage to collect_coverage`:

```
dart --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=NNNN script.dart
dart pub global run coverage:collect_coverage --uri=http://... -o coverage.json --resume-isolates --function-coverage
```

To gather branch level coverage information, pass --branch-coverage to both collect_coverage and the Dart command you're gathering coverage from:

```
dart --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=NNNN --branch-coverage script.dart
dart pub global run coverage:collect_coverage --uri=http://... -o coverage.json --resume-isolates --branch-coverage
```

Branch coverage requires Dart VM 2.17.0, with service API v3.56. Function, branch, and line coverage can all be gathered at the same time, by combining those flags:

```
dart --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=NNNN --branch-coverage script.dart
dart pub global run coverage:collect_coverage --uri=http://... -o coverage.json --resume-isolates --function-coverage --branch-coverage
```

These flags can also be passed to test_with_coverage:

`pub global run coverage:test_with_coverage --branch-coverage --function-coverage`

**Comment by wolfenrain** [comment]
I did a quick test using these commands, and I noticed that Dart enums are not yet supported, they are reported as `functions that arent being hit`

**Comment by tomarra** [comment]
Closing this out as not a current priority. If the Dart enums coverage issue is fixed and there is a need to do the work then we can open up a new issue to track.
