### ISSUE TITLE
docs: make the `README.md` easier to read and navigate

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_workflows#109]
**Description**
The repository has grown significantly. Currently reading the parameters for a specific worfklow requires a decent amount of scrolling or searching.

**Proposal**

Proposal 1: Use markdown tables to simplify the readability.
Proposal 2: Create files documenting each workflow.

(cc: @wolfenrain)

**Comment by scarletteliza** [comment]
Solved with https://github.com/VeryGoodOpenSource/very_good_workflows/pull/124
