### ISSUE TITLE
fix: flutter format is deprecated in workflows/flutter_package.yml@v1

### ISSUE THREAD

**Issue by Shakle** [VeryGoodOpenSource/very_good_workflows#115]
**Description**
When building ci with flutter 3.10 and [workflows/flutter_package.yml@v1](uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1)

I get The "format" command is deprecated. Please use the "dart format" sub-command instead, which has the same command-line usage as "flutter format".

**Steps To Reproduce**

1. Set flutter 3.10 in build params
2. Build
3. On step Check Formatting there will be a deprecation error which stops the process

**Expected Behavior**
It checks for formatting and continues to the next step

**Screenshots**
<img width="1134" alt="screen" src="https://github.com/VeryGoodOpenSource/very_good_workflows/assets/16610897/f36927fc-6536-464c-80b7-204b4517b87b">

**Additional Context**
Flutter 3.10.0+ problem

**Comment by renancaraujo** [comment]
Should be fixed now, could you try again?
