### ISSUE TITLE
docs(semantic_pull_request): add information about GitHub permissions

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_workflows#129]
**Description**

Running out of the box the semantic pull request action will fail with an error:

```sh
Error: Resource not accessible by integration
```

This is because permissions within the GitHub repository need to be updated (from Settings > Actions > General) to allow Read and Write, see image under _Screenshots_ section.

Another option is to include permisisons within the yaml example yaml, see [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token).

**Expected Behavior**
To include information about the required permissions to be able to use the `semantic_pull_request` workflow.

**Screenshots**

![Screenshot 2023-06-25 at 13 18 23](https://github.com/VeryGoodOpenSource/very_good_workflows/assets/44524995/4532f7da-143a-484f-b31f-ecb5c5b9c1bd)

**Comment by jsgalarraga** [comment]
@alestiago  I haven't been able to reproduce this issue. 

I created a [new repo](https://github.com/jsgalarraga/semantic-pull-request-test), added the `semantic_pull_request` workflow in a first PR and worked correctly.

This are the settings that the repository has:
<img width="763" alt="Screenshot 2023-07-20 at 13 50 25" src="https://github.com/VeryGoodOpenSource/very_good_workflows/assets/52668514/fcd3d2d2-e04e-4fbb-94a2-7adf0ede7f5e">

**Comment by alestiago** [comment]
Thanks @jsgalarraga for trying to reproduce. If you make the repository private does it also work for you?

**Comment by jsgalarraga** [comment]
That's the key @alestiago. When making the repository private, the error appears, will work on updating the documentation to explain all this
