### ISSUE TITLE
fix(publish): publish times out if invalid pub credentials are provided

### ISSUE THREAD

**Issue by timcreatedit** [VeryGoodOpenSource/very_good_workflows#133]
**Description**
If you provide an invalid JSON in secrets.PUB_CREDENTIALS, the action tries to authenticate using OAuth. This just waits forever, meaning that the action stalls and only ends once GitHub times it out (6h of valuable Actions minutes for me 🥲)
(Thanks for the awesome actions you provide!)

**Steps To Reproduce**
1. Provide the action with an invalid credentials JSON
2. Run the action
3. pay

**Expected Behavior**
The action should fail if it didn't get any valid credentials

**Additional Context**
```sh
Validating package...
Warning: could not load the saved OAuth2 credentials: FormatException: Failed to load credentials: invalid JSON.

[REDACTED]

Obtaining new credentials...
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A45871&code_challenge=ZDNrLEIfeRs1gmT1yPcofUKYq2H6s7fMx7FXhmqBBT8&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
Error: The operation was canceled.
```

**Comment by ryanaidilp** [comment]
I got this error on my repo as well. Why is this happening though? I copied a valid JSON into my secrets. I even opened the `pub-credentials.json` from VSCode and copied it from there, but it still said `FormatException: Failed to load credentials:`

**Comment by AyushChothe** [comment]
Getting the same error

**Comment by timcreatedit** [comment]
Hey @wolfenrain, thanks for looking at this! I'm not sure if I would consider this issue fixed to be honest, because I think a solution where the action fails immediately if the provided credentials are invalid would address this better. However, 5 minutes are fairly cheap so for all practical purposes it doesn't matter too much I suppose
