### ISSUE TITLE
feat(dart_package): allow --no-example on dart pub get

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_workflows#151]
**Description**
There is a Dart hidden argument (`--no-example`) to avoid getting packages on an `example/` when running `dart pub get`. I would like to be able to toggle this through a workflow parameter.

**Additional Context**
 Including this argument would help using Very Good Workflows on **[Formz](https://github.com/VeryGoodOpenSource/formz/blob/863424a8be583656d6a56a63e334ed7aa6b80274/.github/workflows/main.yaml#L16)**, where the main package does not depend on Flutter but the example does.

**Comment by eliasreis54** [comment]
Hey, @alestiago! I hope you are doing great! 
I applied my first thought to implement this feature. I can replicate it everywhere we run `dart pub get` if you thing it's worth.
