### ISSUE TITLE
chore: Create & Release 1.17.0

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_workflows#194]
**Description**
We have a couple updates to be released since the previous 1.16.1 release.

- Use secrets for confidential information https://github.com/VeryGoodOpenSource/very_good_workflows/pull/182
- add "--no-example" flag in dart pub get https://github.com/VeryGoodOpenSource/very_good_workflows/pull/183
- Dependency updates

**Requirements**

- [x] New release is created
- [x] New release is tagged on GitHub with updated changelog

**Comment by alestiago** [comment]
Moving this to blocked, waiting for the currently open Pull Requests to be merged:

- #197 
- #198
- #199

**Comment by alestiago** [comment]
Closing as completed [1.17.0](https://github.com/VeryGoodOpenSource/very_good_workflows/releases/tag/v1.17.0) is now available and v1 has also been re-tagged for it.
