### ISSUE TITLE
feat: Use the new Automated Publishing documentation for pub.dev packages

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_workflows#213]
**Description**

Given the new [Automated Publishing documentation](https://dart.dev/tools/pub/automated-publishing), we should evaluate it and see how they impact some of our publish workflows.

**Comment by eseidel** [comment]
If you'd like to move to the new ODIC flow, I've written an example that works:
https://github.com/shorebirdtech/updater/blob/f37fee86a9fb1849d8a15da267a2de062d9e17d8/.github/actions/publish_flutter_package/action.yaml

**Comment by tomarra** [comment]
We have updated all of our Dart/Flutter packages to use the https://github.com/dart-lang/setup-dart action. This sets up the needed pub.dev token without having to do the work by hand which @eseidel linked to.

Next step would be to update the workflows here to allow for not passing in a pub token and instead just doing the Dart Setup step automatically.
