### ISSUE TITLE
feat: Could you add a feature request template as I want to suggest a workflow to add next :]

### ISSUE THREAD

**Issue by andreped** [VeryGoodOpenSource/very_good_workflows#232]
I can make a PR for it, if you'd like.

**Comment by alestiago** [comment]
@andreped thanks! I'll assign this to you! 

Here's one in another VeryGoodOpenSource repository that might serve as inspiration: 
- https://github.com/VeryGoodOpenSource/very_good_templates/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by andreped** [comment]
> Here's one in another VeryGoodOpenSource repository that might serve as inspiration:

@alestiago That template is quite clean. What is stopping us from just using this one directly in this repo?

**Comment by alestiago** [comment]
Nothing, feel free to add it yourself as is, that way we can get you as a contributor of the repository too 😉
