### ISSUE TITLE
fix: workflow is not working

### ISSUE THREAD

**Issue by nt4f04uNd** [VeryGoodOpenSource/very_good_workflows#29]
**Description**
Workflow fails on cloning flutter step

**Steps To Reproduce**

1. Run the workflow

**Expected Behavior**
Workflow passes

**Screenshots**
n/a

**Additional Context**
The builds on this commit are red https://github.com/VeryGoodOpenSource/very_good_workflows/commit/b62ee0393c6da47f8fe8d452406b80aa8d217a05

**Comment by mrgnhnt96** [comment]
I was following the guide [here](https://verygood.ventures/blog/configuring-workflows-for-your-flutter-projects?utm_source=github&utm_medium=readme&utm_campaign=workflows_readme). And without and extra config, I am getting this error.

```
Run subosito/flutter-action@v2
Run actions/cache@v2
  with:
    path: /opt/hostedtoolcache/flutter
    key: flutter-stable-
Cache not found for input keys: flutter-stable-
Run $GITHUB_ACTION_PATH/setup.sh -c "/opt/hostedtoolcache/flutter" stable  x64
  $GITHUB_ACTION_PATH/setup.sh -c "/opt/hostedtoolcache/flutter" stable  x64
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Unable to determine Flutter version for channel: stable version: x64 architecture: 
Error: Process completed with exit code 1.
```

**Comment by nt4f04uNd** [comment]
@felangel yeah, thanks, that fixed it

**Comment by mtwichel** [comment]
Chiming in that I had the same issue and the same fix worked for me 🎉  thanks!
