### ISSUE TITLE
feat: automated pub publish workflow

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_workflows#30]
As a Dart/Flutter package developer, I want to have a reusable workflow that will automated the publish to pub.dev.

**Comment by BeatriceMitchell** [comment]
This still needs context to determine what the trigger for automated workflow should be.

**Comment by BeatriceMitchell** [comment]
This will be manually triggered when publishing is desired.

**Comment by renancaraujo** [comment]
After some exploration and conversation, we decided that this is a wontfix.

Reasons:
1 - There is a matter of what value we are giving. There are some actions that take care of publishing and generating a changelog automatically is a too error-prone process. 
2 -  Not everything can be automated: a tag has to be defined manually.
