### ISSUE TITLE
How to generate files before running the workflow?

### ISSUE THREAD

**Issue by adamsmaka** [VeryGoodOpenSource/very_good_workflows#41]
Hello,

Can you tell me how can I execute generating a firebase_option.dart file before running that workflow?

I need to run `echo '${{ secrets.FIREBASE_OPTIONS }}' | base64 --decode > lib/firebase_options.dart` because otherwise analyzer doesn't want to go through.

**Comment by wojtekoziol** [comment]
Hello, 
I have the same issue with [Freezed](https://pub.dev/packages/freezed). I need to run `flutter pub run build_runner build --delete-conflicting-outputs` before running the workflow. 

If you have a way to work with Freezed please let me know!

**Comment by wolfenrain** [comment]
We will look into this to see what possibilities there are to make this possible, if there are any. 

It is a valid question and a good feature to support.

**Comment by wojtekoziol** [comment]
I managed to solve my problem by modifying [the original flutter package workflow](https://github.com/VeryGoodOpenSource/very_good_workflows/blob/main/.github/workflows/flutter_package.yml) to my needs. [Here is my version](https://github.com/wojtekoziol/flash/blob/main/.github/workflows/main.yaml) with added code generation under "Install dependencies" and "Analyze" sections.

I hope this helps!

**Comment by eli1stark** [comment]
I once created a pull request for that https://github.com/VeryGoodOpenSource/very_good_workflows/pull/43. Seems like it's not aligned with the internal VGV flow.

Here is the current up-to-date version with the changes from pr above https://github.com/eli1stark/very_good_workflows. I also added a generator for dart-only apps as well in the current version
