### ISSUE TITLE
fix: `dart_package.yml` fails with `Package spec ".packages" not found, or not a file.`

### ISSUE THREAD

**Issue by Luckey-Elijah** [VeryGoodOpenSource/very_good_workflows#66]
**Description**
When running dart workflow the work flow fails right after all tests pass.

```
🎉 4 tests passed.
Package spec ".packages" not found, or not a file.
```

**Steps To Reproduce**
I have a simple package repository experiencing the issue:
https://github.com/Luckey-Elijah/cached_streamable/runs/8105451027?check_suite_focus=true

**Additional Context**
I image that this is due to the latest dart version (2.18) deprecating the `.packages` usage/directory

**Comment by dionesxxx** [comment]
I'm facing the same here...

**Comment by Luckey-Elijah** [comment]
To add: the `.package` file has
```
# This file is deprecated. Tools should instead consume
# `.dart_tool/package_config.json`.
#
# For more info see: https://dart.dev/go/dot-packages-deprecation
```
So a fix could be updating the `--packages` flag to `--packages=.dart_tool/package_config.json`
