### ISSUE TITLE
feat(flutter_package): support excluding directories

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_workflows#94]
As a developer, I may have directories which I wish to exclude from 'packages get' when using the `flutter_package` workflow but currently, it's not possible to exclude directories from `very_good packages get --recursive`.

**Comment by BeatriceMitchell** [comment]
Blocked by https://github.com/VeryGoodOpenSource/very_good_cli/issues/636

**Comment by felangel** [comment]
> @felangel when you exclude getting the dependencies for a package do you also expect that this package is never tested when using the recursive tests?

I don’t think that’s strictly necessary. The use case for this is mason bricks which contain a pubspec.yaml that contains mustache (causing `dart pub get` to error). It’d probably be most flexible not to assume anything and allow developers to customize which directories are excluded for recursive install and recursive test independently.
