### ISSUE TITLE
fix: GitHub actions failing due to formatting issue

### ISSUE THREAD

**Issue by abdimussa87** [VeryGoodOpenSource/very_good_workflows#97]
**Description**
I'm experiencing a build failure on github actions upon pushing my code. I see that there has been a fix applied that changed flutter format to dart format but for some reason it's calling flutter format on my end.

**Steps To Reproduce**
<img width="717" alt="Screenshot 2023-02-04 at 11 38 21 AM" src="https://user-images.githubusercontent.com/43067015/216757749-4c33319f-bcfd-4c37-8af5-7c60491a5fe4.png">

**Expected Behavior**
GitHub action build succeeding

**Comment by ItsAlexousd** [comment]
`[!] The "format" command is deprecated and will be removed in a future version of Flutter. Please use the "dart format" sub-command instead, which takes all
of the same command-line arguments as "flutter format".`

I assume you are using the flutter_package workflow. Version 1.12.0 fixes this issue but has not been released yet.
Meanwhile, you can modify your workflow like this:

```yaml
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.12.0
```

instead of:

```yaml
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
```

**Comment by 4xMafole** [comment]
Hi, @abdimussa87. I hope the solution works provided by @ItsAlexousd. Would you mind closing the issue?

**Comment by abdimussa87** [comment]
This is what I'm getting now after applying the changes described above:
<img width="643" alt="Screenshot 2023-02-13 at 9 56 14 AM" src="https://user-images.githubusercontent.com/43067015/218391054-5d1a6b5b-52e1-4956-844c-d748cb0c5af7.png">

**Comment by dipakp2726** [comment]
@abdimussa87 please run dart format . and then push

**Comment by abdimussa87** [comment]
Great this has been solved. One question though; how can I update my project created with an older version of very_good_cli when a newer version comes out?
